### ISSUE TITLE
No driver detection

### ISSUE THREAD

**Issue by kamilexg** [ArduCAM/Arducam-Pivariety-V4L2-Driver#2]
Hello,
I have Raspberry Pi 3b+. I have followed this guide: https://www.arducam.com/docs/cameras-for-raspberry-pi/pivariety/how-to-install-kernel-driver-for-pivariety-camera/
After installation I tried to detect the driver. Here is the result:
![image1](https://user-images.githubusercontent.com/84941590/120021911-f85d0e80-bfeb-11eb-9653-352c6ef6bac5.png)
](url)
After a while I got errors:
![error1](https://user-images.githubusercontent.com/84941590/120024178-18420180-bfef-11eb-99b4-73d262dc02a9.png)
![error2](https://user-images.githubusercontent.com/84941590/120024189-1d9f4c00-bfef-11eb-8c50-b2c584253354.png)
![error3](https://user-images.githubusercontent.com/84941590/120024198-2001a600-bfef-11eb-825f-1abf49e2b6ac.png)
![error4](https://user-images.githubusercontent.com/84941590/120024207-21cb6980-bfef-11eb-9241-1b5cc46d9325.png)
![error5](https://user-images.githubusercontent.com/84941590/120024216-23952d00-bfef-11eb-92c5-18b611e106a8.png)
![error6](https://user-images.githubusercontent.com/84941590/120024219-24c65a00-bfef-11eb-9d79-da2e04c90e7c.png)
After these errors, I checked the drivers again and got these results:
![image2](https://user-images.githubusercontent.com/84941590/120024293-3c054780-bfef-11eb-874c-5f4b374d68fb.png)
Please help explain what I am doing wrong.

Regards,

kamilexg

**Comment by kamilexg** [comment]
Now i got this if retry installation driver.
![new](https://user-images.githubusercontent.com/84941590/120563182-44eb8400-c408-11eb-8720-c9e07ede2fcd.png)
I have a damaged camera?

**Comment by mwkldeveloper** [comment]
I have the same problem, the camera never be detected.

**Comment by kamilexg** [comment]
I have a solution. Most likely I didn't have the camera enabled in raspi config. For this I could not install the drivers correctly from this website:
https://www.arducam.com/docs/arducam-obisp-mipi-camera-module/3-use-on-raspberry-pi/3-0-emergent-temporary -driver-for-the-lastest-rpi-2020-12-02-update/

**Comment by AllaboutJay** [comment]
> Now i got this if retry installation driver.
> ![new](https://user-images.githubusercontent.com/84941590/120563182-44eb8400-c408-11eb-8720-c9e07ede2fcd.png)
> I have a damaged camera?

Hello, 

We recommend you follow the DOC:
https://www.arducam.com/docs/cameras-for-raspberry-pi/pivariety/unboxing-video-pivariety-camera/
Note: Please be sure to download the mirror using the link we provided.

and if you still report the error, please send me.

Thanks!
